name: Update Stable Branch

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write
  actions: write

jobs:
  update-stable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create or update stable branch
      run: |
        if [ $(git ls-remote --heads origin stable | wc -l) -eq 0 ]; then
          git checkout -b stable
        else
          git checkout stable
        fi
        git reset --hard ${GITHUB_REF#refs/tags/}
        git push origin stable --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
